const Map<String, dynamic> defaultConfigs = {
  "require_auth_bool": false,
  "app_name_string": "Caster Podcast",
  "seed_color": "#304FFE",
  "podcast_rss_feed_string": "https://www.omnycontent.com/d/playlist/651a251e-06e1-47e0-9336-ac5a00f41628/fc243b66-f34c-4656-9042-acd400edcca5/d4c8e398-446c-447a-ad41-acd400edccc1/podcast.rss",
  "search_string": "Search",
  "threads_string": "Threads",
  "new_thread_string": "New thread",
  "edit_thread_string": "Edit thread",
  "your_next_message_string": "Your next message",
  "thread_icon_string": "Thread icon",
  "thread_name_string": "Thread name",
  "select_users_string": "Select users",
  "save_string": "Save",
  "private_string": "Private",
  "password_reset_string": "Password reset",
  "you_will_receive_email_string": "You will receive an email with a link to reset your password.",
  "cancel_string": "Cancel",
  "continue_string": "Continue",
  "logout_string": "Logout",
  "are_you_sure_question_string": "Are you sure?",
  "delete_account_question_string": "Delete account?",
  "this_action_will_delete_string": "This action will irreversibly delete your account and all your associated data.",
  "delete_string": "Delete",
  "settings_string": "Settings",
  "name_string": "Name",
  "email_string": "Email",
  "password_string": "Password",
  "username_string": "Username",
  "forgot_password_string": "Forgot password?",
  "login_string": "Login",
  "login_with_email_string": "Login with email",
  "login_with_google_string": "Login with Google",
  "create_account_string": "Create account",
  "change_password_string": "Change password",
  "delete_account_string": "Delete account",
  "current_playing_string": "Current playing",
  "clear_local_data_string": "Clear local data",
  "clear_local_data_question_string": "Clear local data?",
  "this_action_will_clear_string": "This action will clear all local data from your device.",
  "clear_string": "Clear",
  "upload_profile_image_string": "Upload profile image",
  "thread_messages_limit_number": 100,
  "thread_limit_number": 100,
  "welcome_to_app_string": "Welcome",
  "are_you_shure_question_string": "Are you sure?",
};