# fly.toml app configuration file generated for caster on 2023-05-26T18:11:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caster"
primary_region = "ams"

[[mounts]]
  source = "data"
  destination = "/app/pb_data"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
