name: iOS

on:
  release:
    types:
      - published
      
jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: app
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    
    - name: Install dependencies
      run: flutter pub get

    - name: Icons
      run: flutter pub run icons_launcher:create

    - name: Test app
      run: flutter test

    - name: Build iOS
      run: flutter build ios --release --no-codesign --dart-define=SERVER_URL=https://${{ github.event.repository.name }}.sandbox.deploid.studio --dart-define=ENVIRONMENT=production --no-tree-shake-icons

    - name: Release IPA
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: app/build/ios/Release-iphoneos/Runner.app